USE GymDW
GO

INSERT INTO Junk VALUES('1','very low')
INSERT INTO Junk VALUES('1','low')
INSERT INTO Junk VALUES('1','medium')
INSERT INTO Junk VALUES('1','high')
INSERT INTO Junk VALUES('1','very high')
INSERT INTO Junk VALUES('2','very low')
INSERT INTO Junk VALUES('2','low')
INSERT INTO Junk VALUES('2','medium')
INSERT INTO Junk VALUES('2','high')
INSERT INTO Junk VALUES('2','very high')
INSERT INTO Junk VALUES('3','very low')
INSERT INTO Junk VALUES('3','low')
INSERT INTO Junk VALUES('3','medium')
INSERT INTO Junk VALUES('3','high')
INSERT INTO Junk VALUES('3','very high')
INSERT INTO Junk VALUES('4','very low')
INSERT INTO Junk VALUES('4','low')
INSERT INTO Junk VALUES('4','medium')
INSERT INTO Junk VALUES('4','high')
INSERT INTO Junk VALUES('4','very high')
INSERT INTO Junk VALUES('5','very low')
INSERT INTO Junk VALUES('5','low')
INSERT INTO Junk VALUES('5','medium')
INSERT INTO Junk VALUES('5','high')
INSERT INTO Junk VALUES('5','very high')
INSERT INTO Junk VALUES('unknown', 'unknown')